apiVersion: v1
kind: ConfigMap
metadata:
  name: asurrance-application-configmap
  namespace: {{ .Values.global.namespace }}
  labels:
    app: assuranse-application-configmap
data:
  IP1: {{ .Values.global.cluster.IP1}}
  IP2: {{ .Values.global.cluster.IP2}}
  IP3: {{ .Values.global.cluster.IP3}}
  NODE1_HOSTNAME: {{ .Values.global.cluster.NODE1_HOSTNAME}}
  NODE2_HOSTNAME: {{ .Values.global.cluster.NODE2_HOSTNAME}}
  NODE3_HOSTNAME: {{ .Values.global.cluster.NODE3_HOSTNAME}}
  KAFKA_BROKERS: {{ .Values.global.cluster.IP1 }}:9092,{{ .Values.global.cluster.IP2 }}:9092,{{ .Values.global.cluster.IP3 }}:9092
  KAFKA_ZK_NODES: {{ .Values.global.cluster.IP1 }}:2181,{{ .Values.global.cluster.IP2 }}:2181,{{ .Values.global.cluster.IP3 }}:2181
  MONGODB_URL: mongodb://{{ .Values.global.cluster.IP1 }}:26000,{{ .Values.global.cluster.IP2 }}:26000,{{ .Values.global.cluster.IP3 }}:26000