---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ml-center-ssh
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ml-center-ssh
    spec:
      nodeSelector:
        node: "1"
      containers:
      - name: ml-center-ssh
        image: harbor.mig.ruijie.net/rgibns-snapshot/ml-center-ssh:1.0
        env:
        - name: TZ
          value: "Asia/Shanghai"
        command: ["/etc/bootstrap.sh"]
        args: ["-c", "(bash /usr/local/ssh-start.sh);(while true; do echo hi; sleep 5; done)"]
        ports:
        - containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: ondp-ml-center-sshd
  namespace: default
spec:
  selector:
    app: ondp-ml-center
  type: NodePort
  ports:
  - nodePort: 39922
    port: 12347
    targetPort: 22
---